baseurl = "https://tasquith.dev/"
languageCode = "en-GB"
title = "Tom Asquith"
# Enable comments by entering your Disqus shortname
disqusShortname = "tomasquith"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Tom Asquith"
  description = ""

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "tomasquith"
  Twitter       = "tomasquith93"
  LinkedIn      = "tomasquith"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
# [[menu.main]]
#   name = "cv"
#   identifier = "cv"
#   weight = 200
#   url = "/cv/"
# [[menu.main]]
#   name = "projects"
#   identifier = "projects"
#   weight = 300
#   url = "/projects/"
